### PR TITLE
Adds sample of probable D, C, and B-class articles for review.

### PR DESCRIPTION
**Pull request by halfak**
This pull request adds a random sample of probable D, C, and B-class articles for review to include in Wikilabels.

### CODE REVIEW

**Comment by halfak** [comment]
https://phabricator.wikimedia.org/T223782

**Review by chrisalbon — APPROVED** [review]
lgtm!

**Comment by halfak** [comment]
I didn't realize that Chris posted a LGTM on this review but it hadn't been merged.  So I continued work on this branch.  New work represents discussion with the nlwiki community.  See https://nl.wikipedia.org/w/index.php?title=Overleg_gebruiker:EpochFail/Kladblok&oldid=60537601#Hodge_podge_of_data_and_building_a_new_ORES_model for discussion of the new pipeline.

**Review by accraze — APPROVED** [review]
:eyes: :+1:

**Pull request merged**
