### PR TITLE
Add new wikidata model

### PR DESCRIPTION
**Pull request by Ladsgroup**
Trained on stat1005

### CODE REVIEW

**Comment by halfak** [comment]
This looks good but it's hard to compare across different datasets so we don't know if the model is better.  It is clear "good" though.  Not a blocker for this PR, but I wonder if there would be a good way to boost the number of "A" observations.  The more balanced the training data is, the better the model will behave and the more useful (fair) the probability estimates will be.

**Comment by halfak** [comment]
Oh!  It looks like the model is not checked in via git lfs.  DO NOT MERGE until this is fixed or it will cause issues.

**Comment by halfak** [comment]
If you haven't yet, you might need to run "git lfs install" on stat1005 in order to set up your local configs.

**Comment by guergana** [comment]
Looks good!

**Pull request merged**
