### PR TITLE
Add features for words that match eu, en, es dicts

### PR DESCRIPTION
**Pull request by kevinbazira**
Add new features for the proportion of words that match Basque, English, and Spanish dictionaries.

### CODE REVIEW

**Comment by halfak** [comment]
It looks like we'll need to add some dictionary installs to our Travis CI (Continuous Integration) image.  
See https://github.com/wikimedia/articlequality/blob/master/.travis.yml for the Travis CI configuration.   You can see that we install English and French dictionaries here: https://github.com/wikimedia/articlequality/blob/master/.travis.yml#L9

You should add the following lines to that list:
```
    - myspell-es
    - hunspell-eu
```

I think that add the spanish and basque dictionaries and that will clear up the errors.

**Comment by accraze** [comment]
@kevinbazira, it seems like TravisCI is still failing due to running on an older Linux distro ('trusty') that does not have access to hunspell-eu. I had a similar issue on our [editquality](https://github.com/wikimedia/editquality/commit/da39cd9b94808bd596b266d439403a200ccff706) library a few months back.

Try updating the dist to a newer version (like xenial) on line 2 in .travis.yml:
```
dist: xenial
```

**Comment by halfak** [comment]
Aha!  We need to do a new revscoring release!  I forgot.

**Comment by halfak** [comment]
I'm closing in favor of https://github.com/wikimedia/articlequality/pull/96 which uses a branch in this repo.

**Pull request closed without merging**
